# Generated by Django 4.1.7 on 2023-02-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumelist',
            name='address',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='award_01',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='award_02',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='award_03',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='award_04',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='award_05',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='c_j_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='c_l_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='college',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='j1_j_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='j1_l_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='j2_j_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='j2_l_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='j3_j_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='j3_l_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='job_details_01',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='job_details_02',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='job_details_03',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='job_title_01',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='job_title_02',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='job_title_03',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='language_01',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='language_02',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='profile_detail',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Picture/'),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='s_j_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='s_l_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='school',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='skill_01',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='skill_02',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='skill_03',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='skill_04',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='skill_05',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='skill_06',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='u_j_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='u_l_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='university',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
    ]
