# Generated by Django 4.1.7 on 2023-02-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_resumelist_address_resumelist_award_01_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumelist',
            name='phone_number',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
