# Generated by Django 4.1.7 on 2023-02-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_resumelist_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumelist',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
