# Generated by Django 4.1.7 on 2023-02-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_resumelist_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumelist',
            name='job_details_01',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resumelist',
            name='job_details_02',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resumelist',
            name='job_details_03',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resumelist',
            name='profile_detail',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
