# Generated by Django 4.1.7 on 2023-02-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_resumelist_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumelist',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
