# Generated by Django 4.1.7 on 2023-02-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_profile_pic_resumelist_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumelist',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
